// src/interfaces/bike.interface.ts

export interface IBike {
    bikeId?: string; // Optional when creating (auto-generated by Prisma)
    brand: string;
    model: string;
    year: number;
    customerId: string;
  }
  